title: cora denning
description: homepage for whatever i want
url: "https://coradenning.site"
baseurl: ""

theme:

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/